inputs:
  name:
    description: "Install frontend"
    default: "No name provided"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.18
    - name: Install frontend Node.js dependencies
      working-directory: frontend
      shell: bash
      run: npm ci
